name: Build

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  release:
    types: [published]
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - main

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    services:
      minio:
        image: fclairamb/minio-github-actions:v0.2
        ports:
          - 9000:9000

    strategy:
      matrix:
        go: [1.18, 1.17]
        include:
          - go: 1.17
            lint: true

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE
      - name: Checkout
        uses: actions/checkout@v3

      - uses: actions/setup-go@v2

      - uses: actions/cache@v3.0.2
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
            ~/go/bin
          key: ${{ runner.os }}-${{ matrix.go }}-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.go }}-

      # Running golangci-lint
      - name: Run golangci-lint
        if: matrix.lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.45.2

      - name: Install Task
        uses: arduino/setup-task@v1

      # Install Go
      - name: Setup go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go }}

      - name: Test
        # We need GCC because of the "go test -race"
        env:
          CGO_ENABLED: 1
        run: task run-test

  # For github to have a unique status check name
  status:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - run: echo 'All good'
